### ISSUE TITLE
Add `autopep8` to the tools

### ISSUE THREAD

**Issue by kytta** [tox-dev/pyproject-fmt#104]
I use `autopep8` as formatter (don't judge), and it gets pushed at the very end of my pyproject.toml. I expect it to be a bit higher. My guess is that I need to adjust the `fmt_tools()` method and place it somewhere close to `black`.

Speaking of it, how do the tools get their sorting order. They're not alphabetical, but categorical? If so, why is Ruff (linter) above isort (formatter)?

https://github.com/tox-dev/pyproject-fmt/blob/86892dff50a0969c300d7281cc105d39b5ee4256/src/pyproject_fmt/formatter/tools.py#L29-L41

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by gaborbernat** [comment]
> If so, why is Ruff (linter) above isort (formatter)?

ruff has auto-fixes that changes code. TO be fair I'd be ok to swap ruff and isort ordering.
