### ISSUE TITLE
question: dependency format specification in `pyproject.toml`

### ISSUE THREAD

**Issue by yarnabrina** [tox-dev/pyproject-fmt#135]
We have recently started using `pyproject-fmt` in `sktime`, and we are getting into conflicts with `dependabot`. This formatter prefers the style of `"holidays<0.36,>=0.29"` over `"holidays>=0.29,<0.36"`, whereas `dependabot` does the opposite. It can be seen in the CI logs of https://github.com/sktime/sktime/pull/5443.

Is there any way to control this behaviour via configuration?

**Comment by gaborbernat** [comment]
We follow the style suggested by the pypa standard lib https://github.com/pypa/packaging, so IMHO in this case dependabot should change.
