### ISSUE TITLE
Removes 3.6 classifier

### ISSUE THREAD

**Issue by amotl** [tox-dev/pyproject-fmt#137]
Dear @gaborbernat,

thanks a stack for conceiving and maintaining this excellent package.

Following up on GH-106, we would like to point out https://github.com/panodata/verlib2/pull/8, where a recent version of `pyproject-fmt` removes the Python 3.6 classifier. We know it is EOL, but some packages still want to support it.

With kind regards,
Andreas.

**Comment by gaborbernat** [comment]
We do respect the value set in pyproject.toml https://github.com/tox-dev/pyproject-fmt/blob/main/src/pyproject_fmt/formatter/project.py#L67C5-L67C13 so it really shouldn't. PR welcome if the bug is on our side.

**Comment by amotl** [comment]
> PR welcome if the bug is on our side.

Thank you. While not 100% correct, GH-138 fixes the issue for us.

**Comment by amotl** [comment]
To elaborate a bit why the fix is not 100% solid, other than what has been outlined in the PR description:

1. The default value of `_PY_MIN_VERSION` is already used at [L67](https://github.com/tox-dev/pyproject-fmt/blob/1.2.0/src/pyproject_fmt/formatter/project.py#L67).
2. Then, it is also used at [L76](https://github.com/tox-dev/pyproject-fmt/blob/1.2.0/src/pyproject_fmt/formatter/project.py#L76), which is probably not intended. Instead, it should be derived from the parsed `SpecifierSet` in `specifiers`, which already resolved the `requires-python` setting, but differently than it is done right now, also considering "minimum versions" instead of just resolving the `max_version_specifier`.

**Comment by gaborbernat** [comment]
I cannot accept an incorrect solution though 🤔

**Comment by amotl** [comment]
I am sharing your sentiment. There is clearly a flaw in the logic, and the test suite does not catch it, just to outline that it is not a special case, and will trip in other situations as well.

**Comment by amotl** [comment]
Oh, the test suite actually fails, demonstrating that my fix makes it worse. It looks like I am having a very bad day, apologies Bernát.

**Comment by amotl** [comment]
The patch GH-138 has been amended according to your suggestions to do it in the right way. Thanks for your patience.
