### ISSUE TITLE
Request: (option to) keep `.0` at the end of dependency versions

### ISSUE THREAD

**Issue by adamtheturtle** [tox-dev/pyproject-fmt#141]
Thank you for this project.

If a dependency version is `2.1.0`, for example, `pyproject-fmt` will change that to `2.1`.
I have not seen this in other tooling.
For example, https://pypi.org/project/pyproject-fmt/ currently shows `pyproject-fmt 1.3.0`, and not `pyproject-fmt 1.3` as the current version.

Where it becomes annoying In my projects so far is with [GitHub's Dependabot](https://github.com/dependabot).
Dependabot will bump a package to `1.3.0` and then `pyproject-fmt` will fail in CI because of the difference between the new and expected package version.
I have options either to fix all of these manually (effort + CI runs), or to create tooling to run `pyproject-fmt` after Dependabot runs, or to move `pyproject-fmt` out of my normal, blocking, lint build.

I'm not against contributing, but would like to have an approval of the idea / understanding of what might be accepted. For example, would it be an option with default `false`?

**Comment by gaborbernat** [comment]
> For example, would it be an option with default `false`?

PR welcome 👍

**Comment by adamtheturtle** [comment]
Looking forward to a release :)

In the meantime, be aware that the documentation at https://pyproject-fmt.readthedocs.io/en/latest/ now has the new CLI flag, but the latest release does not. In some projects, I avoid linking to `/latest` for this reason.

**Comment by adamtheturtle** [comment]
Though I see you've just released!
