### ISSUE TITLE
Which section will be formatted?

### ISSUE THREAD

**Issue by njzjz** [tox-dev/pyproject-fmt#151]
I tried to use this tool, but the behavior confused me. While it formats lists in `[build-system]` and `[project]` to make the indent have two spaces, it entirely ignores the indent in `[tool]` section.

![image](https://github.com/tox-dev/pyproject-fmt/assets/9496702/679f7099-afd0-404f-9c77-e97e734a955f)

![image](https://github.com/tox-dev/pyproject-fmt/assets/9496702/a512c35c-718b-4ddb-853a-6af9286cede7)

Is it the expected behavior?

**Comment by gaborbernat** [comment]
It only handles the build-system and project sections for now. PR welcome to change that.
