### ISSUE TITLE
Feature request: A VSCode extension so that pyproject-fmt runs on save of pyproject.toml

### ISSUE THREAD

**Issue by adamtheturtle** [tox-dev/pyproject-fmt#165]
I have found this useful useful with Ruff (https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff), and I would like the same for `pyproject-fmt`.

**Comment by gaborbernat** [comment]
Out of scope for this PR, but you are welcome to create a project for that yourself and share it here.
