### ISSUE TITLE
Enforce single line `description`

### ISSUE THREAD

**Issue by edgarrmondragon** [tox-dev/pyproject-fmt#183]
And maybe make it opt-in. This tool already strips whitespace from the field:

https://github.com/tox-dev/pyproject-fmt/blob/bb6005786f6624d72a66b7be876696a788ce7414/src/pyproject_fmt/formatter/project.py#L41-L42

Related:

* https://github.com/pypa/packaging.python.org/pull/1533
* https://github.com/pypa/pyproject-metadata/issues/30
* https://github.com/pypa/pyproject-metadata/pull/76
* https://packaging.python.org/en/latest/specifications/core-metadata/#summary

**Comment by gaborbernat** [comment]
I would be okay to accept a pull request in this direction.

**Comment by henryiii** [comment]
Would it make sense to turn [this]():

```toml
description = """A Machine learning library that models and predicts learner engagement
                 with educational resources."""
```

Into this:

```toml
description = "A Machine learning library that models and predicts learner engagement with educational resources."
```

Or this:
```toml
description = """A Machine learning library that models and predicts learner engagement\
                 with educational resources."""
```


? Both are fine IMO, though I prefer the first, as this isn't supposed to be a really long line (it's displayed on PyPI, etc).

More fun ones are ones like https://github.com/Abdel-RahmanSaied/mediaSecure/blob/caabcf86622a519a55a99f604d8dad60a27f94bc/pyproject.toml#L11-L47 :)

**Comment by edgarrmondragon** [comment]
I've started #184 with the first option above as the goal.
