### ISSUE TITLE
pyproject-fmt unexpectedly lowercases requirements names

### ISSUE THREAD

**Issue by adamtheturtle** [tox-dev/pyproject-fmt#199]
I have the requirement `types-PyYAML` which matches https://pypi.org/project/types-PyYAML/.
`pyproject-fmt` as of `2.0.0` changes this to `types-pyyaml`.

**Comment by gaborbernat** [comment]
This is expected, we use now the canonical name.

**Comment by gaborbernat** [comment]
Note this will not break anything, the two are equal from a
Python point of view.
