### ISSUE TITLE
API documentation section essentially empty

### ISSUE THREAD

**Issue by adamtheturtle** [tox-dev/pyproject-fmt#200]
Visit https://pyproject-fmt.readthedocs.io/en/latest/#module-pyproject_fmt, see:

<img width="758" alt="Screenshot 2024-05-11 at 10 01 22" src="https://github.com/tox-dev/pyproject-fmt/assets/797801/d0d078a3-13d3-4d94-9924-1532555f281b">

This section should either be removed or changed to explain an API.

**Comment by gaborbernat** [comment]
I think let's remove it, PR welcome.

**Comment by gaborbernat** [comment]
Done via https://github.com/tox-dev/pyproject-fmt/releases/tag/2.0.3

**Comment by abravalheri** [comment]
Does this mean that developers using the API should use https://github.com/tox-dev/pyproject-fmt-rust instead (I understand that one is currently undocumented but supposedly that is a WIP)?

**Comment by gaborbernat** [comment]
What's your use case?

**Comment by abravalheri** [comment]
For now, I would like to be able to run `pyproject-fmt` (with its default configurations) on a `str` variable.

That is used in [`ini2toml`](https://ini2toml.readthedocs.io/en/latest/).

Previously I was running `format_pyproject(Config(Path("pyproject.toml"), text))`

**Comment by gaborbernat** [comment]
The rust package has no defaults. Today, your best chance would be to just do a sub process call. We could expose an endpoint for this functionality though. PR welcome 🤗

**Comment by abravalheri** [comment]
OK, I think in this case that might be a regression on https://github.com/tox-dev/pyproject-fmt/issues/3?

**Comment by gaborbernat** [comment]
We changed the interface, so the new API would also need to look differently.

**Comment by abravalheri** [comment]
Thanks @gaborbernat, I will give another go at reimplementing the feature with a new look.

**Comment by gaborbernat** [comment]
So if I understand this correctly you are not really interested in the fancy diff or check functionality. You just want to format the file after generating it with no output, Yes?

**Comment by gaborbernat** [comment]
Fixed via https://github.com/tox-dev/pyproject-fmt/releases/tag/2.1.0
