### ISSUE TITLE
Bug for array table

### ISSUE THREAD

**Issue by Piyatap** [tox-dev/pyproject-fmt#213]
`pyproject-fmt` removes the instance of array table with double square brackets `[[ ... ]]` since version 2.0.0.

![image](https://github.com/tox-dev/pyproject-fmt/assets/63843616/e0d988e7-e508-4f47-b379-8309a6fc5d75)

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by gaborbernat** [comment]
Do you have link to repro file?

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/pyproject-fmt-rust/pull/17 would fix it

**Comment by gaborbernat** [comment]
Fixed via https://github.com/tox-dev/pyproject-fmt/releases/tag/2.1.0
