### ISSUE TITLE
Add an option that controls whether lists are sorted

### ISSUE THREAD

**Issue by nathanjmcdougall** [tox-dev/pyproject-fmt#234]
It would be great to have a setting which configures whether lists are sorted or not.

My rationale is that sometimes it is helpful to be able to organize list elements into groups with comments etc. For example, linter rule codes.

**Comment by gaborbernat** [comment]
We are aiming to be similar to the Black formatter. The less configuration the better. The only kind of contribution I would accept is a fmt on/off comment block.

**Comment by nathanjmcdougall** [comment]
Okay, that's a fair decision. Would you accept an update to the docs which says so explicitly? E.g. a Philosophy paragraph.

**Comment by gaborbernat** [comment]
Definitely 😃
