### ISSUE TITLE
Allow for reading from stdin

### ISSUE THREAD

**Issue by fniessink** [tox-dev/pyproject-fmt#238]
I'd like to configure pyproject-fmt as [formatter in Zed](https://zed.dev/docs/configuring-zed#formatter). Formatters in Zed need to be able to read from stdin and write to stdout. It seems pyproject-fmt can do the latter, but not the former. 

Is this something you would consider adding? I can provide a PR if you'd like.

I was thinking of adding this as flag under run mode:

```  
run mode:
   -s, --stdout          print the formatted TOML to the stdout (default: False)
   -i, --stdin           read the TOML to format from the stdin (default: False)
```

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by fniessink** [comment]
PR opened (#239). I opted for using '-' to signify reading from stdin as it seemed a bit easier to implement: no need for extra flags in the CLI nor in the code.
