### ISSUE TITLE
Repo root `tool.pyproject-fmt` not applying to sub-`pyproject.toml`

### ISSUE THREAD

**Issue by jamesbraza** [tox-dev/pyproject-fmt#240]
With `pyproject-fmt==2.1.4`, in a `pyproject.toml` in my repo root, I configured the following:

```toml
[tool.pyproject-fmt]
indent = 4
```

However this setting does not propagate to `pyproject.toml` in subfolders of the repo root. For example, a TOML list in `subfolder/pyproject.toml` is getting 2-space indents.

The request here is to have settings configured the root folder's `pyproject.toml` apply to subfolders.

**Comment by gaborbernat** [comment]
There is no inheritance of the configuration. Every file has the configuration applied only for itself.
