### ISSUE TITLE
Request: supporting alphabetization of keys

### ISSUE THREAD

**Issue by jamesbraza** [tox-dev/pyproject-fmt#241]
I use https://github.com/pappasam/toml-sort, which alphabetizes keys. However, `pyproject-fmt==2.1.4` then un-alphabetizes the keys.

Is there some way we can add a flag to support alphabetic ordering of keys in `pyproject-fmt`?

**Comment by gaborbernat** [comment]
These two projects have opposing philosophies and probably should be used exclusively.
