### ISSUE TITLE
Request: not adding spaces before brackets

### ISSUE THREAD

**Issue by jamesbraza** [tox-dev/pyproject-fmt#242]
I use [pappasam/toml-sort](https://github.com/pappasam/toml-sort), which removes spaces within TOML list brackets. However, `pyproject-fmt==2.1.4` enforces spaces within TOML list brackets.

To be more concrete, when going from `toml-sort`'d TOML to `pyproject-fmt`'d TOML:

```diff 
---list = ["value"]
+++list = [ "value" ]
```

I preter the `toml-sort` style here of tight brackets because it aligns with [PEP 8](https://peps.python.org/pep-0008/) formatting.

The request is, can `pyproject-fmt` add an opt-in flag to not add spaces within TOML list brackets

**Comment by gaborbernat** [comment]
These two projects have opposing philosophies and probably should be used exclusively.
