### ISSUE TITLE
Outdated URLs in project metadata?

### ISSUE THREAD

**Issue by mgorny** [tox-dev/pyproject-fmt#27]
The URLs in project metadata (and therefore PyPI) refer to [gaborbernat's fork](https://github.com/gaborbernat/pyproject-fmt/). However, it seems that the tags for the latest releases are only in this repo. Is this the correct repository then? If yes, could you please update the URLs to avoid confusion?

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/pyproject-fmt/commit/7a487c07132281f89a16a00d80910f90c0be8e61

**Comment by mgorny** [comment]
Thank you!
