### ISSUE TITLE
Replaces underscore with dash in name

### ISSUE THREAD

**Issue by okken** [tox-dev/pyproject-fmt#55]
Cool project.  
I agree with most of the recommendations by the tool when I tried it on a pytest plugin.

However, it incorrectly changed the name from `name = "pytest-something"` to `name = "pytest_something"`.  
That's wrong.  It's traditional for pytest plugins to be named pytest-something.

pyproject-fmt can move the name around in the file, but it shouldn't change the name of the project.

Example pyproject.toml:
```
[project]
name = "pytest-something"
```

Running `pyproject-fmt pyproject.toml` results in:
```
[project]
name = "pytest_something"
```

It seems very odd for changing the name at all to be a correct behavior, pytest plugin or not.

**Comment by RonnyPfannschmidt** [comment]
i also was bitten by this
even more so as my understanding of https://packaging.python.org/en/latest/specifications/name-normalization/ means that pyproject_fmt take a normalized name and denormalizes it

today this behaviour triggered a issue with code that was handling only strictly normalized names correctly as the application of pyproject-fmt caused a change, i'll link more details later

**Comment by RonnyPfannschmidt** [comment]
@gaborbernat would a config option for this be accepted?

**Comment by gaborbernat** [comment]
I don't think we need a config, what we need is to apply the correct normalization 😆

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/pyproject-fmt/blob/main/src/pyproject_fmt/formatter/project.py#L21 should instead do https://packaging.python.org/en/latest/specifications/name-normalization/#normalization

**Comment by RonnyPfannschmidt** [comment]
@gaborbernat i may be able to get back to this later

**Comment by hugovk** [comment]
Please see PR https://github.com/tox-dev/pyproject-fmt/pull/66.
