### ISSUE TITLE
Add `--check`

### ISSUE THREAD

**Issue by bollwyvl** [tox-dev/pyproject-fmt#64]
Thanks for this useful tool!

Following the conventions of other CLI tools (e.g. `isort`, `black`) might make this a little more familiar and easy to integrate into larger static analysis suites.

I think a key one is `--check`, which would see if it _would_ make a change, and _maybe_ print out a diff, but definitely _not_ update anything, and return a failing return code.

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by bollwyvl** [comment]
https://github.com/tox-dev/pyproject-fmt/pull/65 is up...
